# Generated by Django 4.2.1 on 2024-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Tech_stack', models.CharField(choices=[('P', 'Python'), ('H', 'Html'), ('S', 'Sql'), ('D', 'Django'), ('Dl', 'Data Science Libraries'), ('C', 'CSS'), ('J', 'Java Script'), ('G', 'Git')], max_length=2)),
                ('email', models.EmailField(max_length=50)),
                ('Mobile_num', models.IntegerField()),
            ],
        ),
    ]
