# Generated by Django 4.2.1 on 2024-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_group',
            name='Mobile_num',
            field=models.CharField(max_length=12),
        ),
    ]
